### ISSUE TITLE
should be able to associate a color with a meeting type

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/calendar-assistant#12]
I'm imagining a way to configure an association of a color with a meeting type:

```yaml
style:
  - meeting_type: 1-1
    color: basil
  - meeting_type: self
    color: sage
```

so that when meetings are created/rescheduled/etc. the color is set appropriately
