### ISSUE TITLE
defensively preserve remaining time during a day

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/calendar-assistant#6]
When my calendar for the day is nearly full,
Linting should create "self + busy" events filling the remaining time,
So that I get some thinking time.

---

(This needs to be broken down into smaller stories.)

An interesting concept to explore here is: what is "nearly full"? Some ideas:

- There's only one 60-minute block left (i.e. save a big chunk of time)
- There's more than N minutes of meetings scheduled already (i.e., put a ceiling on how much time I'm with other people)

Also see #2 for related discussion.

In my head I'm imagining some user config like:

```yaml
defense:
  - type: save-chunk
    options:
      length: 60m
```

or

```yaml
defense:
  - type: busy-ceiling
    options:
      max: 360
      ignore: "< 25m"
```

and then running something like:

```
calendar-assistant lint --defense today
```

would check my calendar for the day and take action.
