### ISSUE TITLE
Ability to add location to multiple calendars

### ISSUE THREAD

**Issue by joshknowles** [flavorjones/calendar-assistant#63]
Fill in cli workflow later...

- [x] #85

**Comment by mikfreedman** [comment]
(this is @flavorjones )

from CLI:

```
calendar-assistant location-set ---calendars=CALID1[,CALID2[,...]] Here
```

and then we can set the default in the command-specific configuration:

```toml
[settings.location_set]
calendars = "CALID1,CALID2,CALID3"
```

step 3: magic.

NOTE: this is dangerous on a shared calendar. We need to raise an exception if we try to do this and your `nickname` isn't set. And we should document the nickname collision problem in the README.
